name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npm run prettier-check

      - name: Run lint
        run: npm run lint-check

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.COLOCAR_TOKEN_DE_NPM_NUEVO }}
        run: npx semantic-release